//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agranillo.ToDoList.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agranillo.ToDoList.App.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ItemPage_Alert_Accept {
            get {
                return ResourceManager.GetString("ItemPage.Alert.Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t save your changes. Please, try again..
        /// </summary>
        internal static string ItemPage_Alert_Message {
            get {
                return ResourceManager.GetString("ItemPage.Alert.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ItemPage_Alert_Title {
            get {
                return ResourceManager.GetString("ItemPage.Alert.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ItemPage_Page_Description {
            get {
                return ResourceManager.GetString("ItemPage.Page.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string ItemPage_Page_Finished {
            get {
                return ResourceManager.GetString("ItemPage.Page.Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ItemPage_Page_Save {
            get {
                return ResourceManager.GetString("ItemPage.Page.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ItemPage_Page_Title {
            get {
                return ResourceManager.GetString("ItemPage.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item.
        /// </summary>
        internal static string ItemPage_Title_Creating {
            get {
                return ResourceManager.GetString("ItemPage.Title.Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        internal static string ItemPage_Title_Editing {
            get {
                return ResourceManager.GetString("ItemPage.Title.Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MainPage_Delete_Confirm_Accept {
            get {
                return ResourceManager.GetString("MainPage.Delete.Confirm.Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MainPage_Delete_Confirm_Cancel {
            get {
                return ResourceManager.GetString("MainPage.Delete.Confirm.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        internal static string MainPage_Delete_Confirm_Message {
            get {
                return ResourceManager.GetString("MainPage.Delete.Confirm.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MainPage_Delete_Confirm_Title {
            get {
                return ResourceManager.GetString("MainPage.Delete.Confirm.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MainPage_Delete_Result_Accept {
            get {
                return ResourceManager.GetString("MainPage.Delete.Result.Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was successfully removed..
        /// </summary>
        internal static string MainPage_Delete_Result_Message {
            get {
                return ResourceManager.GetString("MainPage.Delete.Result.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string MainPage_Delete_Result_Title {
            get {
                return ResourceManager.GetString("MainPage.Delete.Result.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string MainPage_Page_New {
            get {
                return ResourceManager.GetString("MainPage.Page.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo List.
        /// </summary>
        internal static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage.Title", resourceCulture);
            }
        }
    }
}
